name: Automation Exam

on: [push]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install pytest pytest-html flake8
          pip install -r requirements.txt

      
      - name: Lint with flake8
        run: flake8 . || true

      - name: Test with pytest
        run: PYTHONPATH=. pytest --html=report.html --self-contained-html

      - name: Upload Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: python-report-${{ matrix.python-version }}
          path: report.html

  build-docker:
    needs: test-and-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t my-app .
